export const slotProProducts = [
  [
    {
      name: 'Энергетический Кофе',
      description: 'Крепкий эспрессо для бодрого начала дня.',
      price: 15,
      count: 1,
      image: require('../assets/aromatniy.png'),
    },
    {
      name: 'Шоколадный Напиток',
      description:
          'Горячий шоколад с насыщенным вкусом, украшенный сливками.',
      price: 15,
      count: 1,
      image: require('../assets/goryachiy.png'),
    },
    {
      name: 'Свежие Соки',
      description: 'Апельсиновый, яблочный и грейпфрутовый соки.',
      price: 10,
      count: 1,
      image: require('../assets/fresh.png'),
    },
    {
      name: 'Матча Латте Особый',
      description: 'Матча с молоком и натуральным сиропом.',
      price: 20,
      count: 1,
      image: require('../assets/matcha.png'),
    },
  ],
  [
    {
      name: 'Торт "Ягодный Взрыв"',
      description: 'Бисквит с ягодным кремом и свежими ягодами.',
      price: 50,
      count: 1,
      image: require('../assets/lesnaya.png'),
    },
    {
      name: 'Манговый Десерт',
      description: 'Мусс из манго с воздушным бисквитом.',
      price: 40,
      count: 1,
      image: require('../assets/mango.png'),
    },
    {
      name: 'Безе с Ягодами',
      description: 'Десерт с безе, ягодами и кремом.',
      price: 35,
      count: 1,
      image: require('../assets/pavlova.png'),
    },
    {
      name: 'Торт "Цитрусовая Феерия"',
      description: 'Лимонный курд на песочной основе с меренгой.',
      price: 45,
      count: 1,
      image: require('../assets/limonniy_ray.png'),
    },
  ],
  [
    {
      name: 'Торт "Классика"',
      description: 'Слоеное тесто с нежным сливочным кремом.',
      price: 20,
      count: 1,
      image: require('../assets/napaleon.png'),
    },
    {
      name: 'Медовый Десерт',
      description: 'Медовый торт с легким сливочным вкусом.',
      price: 20,
      count: 1,
      image: require('../assets/medovik.png'),
    },
    {
      name: 'Шоколадный Взрыв',
      description: 'Насыщенный шоколадный торт с кремом.',
      price: 55,
      count: 1,
      image: require('../assets/shokoladniy.png'),
    },
    {
      name: 'Итальянский Тирамису',
      description: 'Традиционный десерт с маскарпоне и кофе.',
      price: 45,
      count: 1,
      image: require('../assets/tiramisu.png'),
    },
  ],
  [
    {
      name: 'Французские Макароны',
      description: 'Разноцветные макароны с разнообразными начинками.',
      price: 10,
      count: 1,
      image: require('../assets/makarun.png'),
    },
    {
      name: 'Кремовые Эклеры',
      description: 'Эклеры с нежным кремом и глазурью.',
      price: 15,
      count: 1,
      image: require('../assets/ekleri.png'),
    },
    {
      name: 'Праздничные Капкейки',
      description: 'Капкейки с разными вкусами и ярким декором.',
      price: 20,
      count: 1,
      image: require('../assets/kapkeyki.png'),
    },
    {
      name: 'Шоколадные Трюфели',
      description: 'Трюфели с разнообразными начинками.',
      price: 45,
      count: 1,
      image: require('../assets/tryufeli.png'),
    },
  ],
];
